<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Spokesoft.Test</PackageId>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>spokesoft</ToolCommandName>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>Spokesoft</Authors>
    <Company>Spokesoft</Company>
    <Description>Project management tool for the command line</Description>
    <PackageTags>tool cli dotnet agile scrum</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageProjectUrl>https://github.com/spokesoft/test</PackageProjectUrl>
    <RepositoryUrl>https://github.com/spokesoft/test.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

</Project>