<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.1</Version>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Spokesoft.Test</PackageId>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>spokesoft</ToolCommandName>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>Spokesoft</Authors>
    <Company>Spokesoft</Company>
    <Description>Project management tool for the command line</Description>
    <PackageTags>tool cli dotnet agile scrum</PackageTags>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageProjectUrl>https://github.com/spokesoft/Spokesoft.Test</PackageProjectUrl>
    <RepositoryUrl>https://github.com/spokesoft/Spokesoft.Test.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <IncludePackageLicenseFile>true</IncludePackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>